version: "3.8"

services:
  django:
    build: .
    container_name: django
    env_file:
      - .env.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/project/
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    command: celery -A project worker -l INFO
    volumes:
      - .:/usr/src/project
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - .env.db
    volumes:
       - pgdata:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
volumes:
  pgdata: