# Generated by Django 3.2.4 on 2021-06-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Wait'), (2, 'Cook'), (3, 'On the way'), (4, 'Delivered')], default=1)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket_app.basket')),
            ],
        ),
    ]
