# Generated by Django 3.2.4 on 2021-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Wait'), (2, 'Cook'), (3, 'On the way'), (4, 'Delivered')], default=1)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
        ),
    ]
