# Generated by Django 3.2.4 on 2021-07-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
        ('user_app', '0001_initial'),
        ('complaint_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.courier'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_app.order'),
        ),
    ]
